version: '3.5'

services:

  app:
    restart: always
    build: .
    image: api
    container_name: app
    ports:
      - "5000:5000"
    
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - /Users/me/Developement/APP/django/api/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
